title: M_Xav blog
author: Xav83
email: xavier.jouvenot@10xlearner.com
description: > # this means to ignore newlines until "baseurl:"
  Blog created during the GitHub Pages course on GitHub Learning Lab - https://lab.github.com/githubtraining/github-pages

theme: minima

# social links
twitter_username: 10xLearner # DO NOT include the @ character, or else the build will fail!
github_username:  Xav83 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
